In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
train_set = pd.read_csv("train.csv")
test_set = pd.read_csv("test.csv")

In [3]:
#Finding correlation between the features
print(train_set.corr())

                     Id  MSSubClass  LotFrontage   LotArea  OverallQual  \
Id             1.000000    0.011156    -0.010601 -0.033226    -0.028365   
MSSubClass     0.011156    1.000000    -0.386347 -0.139781     0.032628   
LotFrontage   -0.010601   -0.386347     1.000000  0.426095     0.251646   
LotArea       -0.033226   -0.139781     0.426095  1.000000     0.105806   
OverallQual   -0.028365    0.032628     0.251646  0.105806     1.000000   
OverallCond    0.012609   -0.059316    -0.059213 -0.005636    -0.091932   
YearBuilt     -0.012713    0.027850     0.123349  0.014228     0.572323   
YearRemodAdd  -0.021998    0.040581     0.088866  0.013788     0.550684   
MasVnrArea    -0.050298    0.022936     0.193458  0.104160     0.411876   
BsmtFinSF1    -0.005024   -0.069836     0.233633  0.214103     0.239666   
BsmtFinSF2    -0.005968   -0.065649     0.049900  0.111170    -0.059119   
BsmtUnfSF     -0.007940   -0.140759     0.132644 -0.002618     0.308159   
TotalBsmtSF   -0.015415  

SalePrice is correlated to OverallQual, YearBuilt, YearRemodAdd, TotalBsmtSF, 1stFlrSF, GrLivArea, FullBath, TotRmsAbvGrd, GarageCars, GarageArea (over 0.5 or under -0.5)

In [4]:
# For highly correlated
# X = train_set.loc[:, ["OverallQual", "YearBuilt", "YearRemodAdd", "TotalBsmtSF", "1stFlrSF", "GrLivArea", "FullBath", "TotRmsAbvGrd", "GarageCars", "GarageArea"]].values
# y = train_set.iloc[:, -1].values

In [ ]:
# For lowly correlated
# X = train_set.loc[:, ["OverallQual", "YearBuilt", "YearRemodAdd", "TotalBsmtSF", "1stFlrSF", "GrLivArea", "FullBath", "TotRmsAbvGrd", "GarageCars", "GarageArea"]].values
# y = train_set.iloc[:, -1].values

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=0)

In [6]:
# X_test = test_set.loc[:, ["OverallQual", "YearBuilt", "YearRemodAdd"]].values
# y_test = test_set.iloc[:, -1].values

In [7]:
print(X_train)
print(y_train)

[[   8 2007 2007 ...    7    2  567]
 [   4 1956 1956 ...    5    1  288]
 [   8 2006 2007 ...    6    3  870]
 ...
 [   6 1978 1978 ...    8    2  539]
 [   7 2003 2004 ...    7    2  420]
 [   7 1998 1998 ...    7    2  486]]
[392000 112000 248900 ... 112000 234000 221000]


In [8]:
print(X_test)
print(y_test)

[[   6 1957 1975 2035 2515 2515    3    9    2  484]
 [   6 1941 1950  806  958 1578    1    5    1  240]
 [   5 1950 1950  709  979 1203    1    5    1  352]
 [   7 1977 1977 1160 1156 2022    2    8    2  505]
 [   6 1971 1971  525  525 1092    1    6    1  264]
 [   5 1910 2006 1022 1022 1022    1    4    1  280]
 [   8 2007 2007 1485 1464 1464    2    6    3  754]
 [   6 1937 1950  780  780 1375    1    6    1  544]
 [  10 1996 1996 2396 2411 4476    3   10    3  813]
 [   7 2004 2004  551  551 1102    2    4    2  480]
 [   7 2006 2007 1352 1352 1352    2    5    2  466]
 [   5 1976 1976 1680 1680 1680    2    8    2  528]
 [   7 1999 1999  978 1005 1983    2    9    2  490]
 [   5 1967 1967  864  900  900    1    6    1  288]
 [   6 1948 1950 1082 1082 1082    1    5    1  240]
 [   5 1957 1957 1314 1314 1314    1    5    1  294]
 [   7 1992 1992  750 1061 1923    2    8    2  564]
 [   4 1994 1995  990  990  990    1    5    0    0]
 [   5 1966 2006 1228 1228 1228    1    6    1

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [10]:
linear_regression_model = LinearRegression()
linear_regression_model.fit(X_train, y_train)

LinearRegression()

In [11]:
y_pred = linear_regression_model.predict(X_test)

In [12]:
print(y_pred)

[253663.77322253 144316.4153415  110480.88559506 224329.76375837
 126642.24237348 114193.60284578 258902.37439773 137661.86583023
 458256.57558511 171392.60523411 212916.64270867 187704.66312888
 230229.13837243 108912.26091274 131500.93275645 135315.41417586
 219737.33552355  95570.25952339 147051.43836564 188783.31870653
 134772.35898399 155639.93707314 113587.78435522 169049.61948993
 188734.4305162  207202.38852993 178317.76130142  50566.27832908
 300172.4320016  111773.08181157 199367.23230094 208999.61836776
 148027.22508679 281630.50673144 307707.14904561 190338.52987666
 270971.90367775 122901.34502883 235533.1721002  296307.91902236
 226829.51064579 135059.87219932 209134.71404975 289694.28472657
 316436.49628135 174323.68062127 124110.57301117 113015.34325676
 179304.77445457  81046.11086206 338590.89402748 136420.28129075
 179769.79224696  51141.51550395 225347.22876261 122950.29013555
 122646.50540513 256211.61173721 137041.42052369  88818.91548814
 150645.37182912 115135.2

In [13]:
mean_squared_error(y_test, y_pred)

1981699804.6586564